backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

collections:
    - label: "Services"
      name: "services"
      create: true
      folder: "src/services"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Icon", name: "faIcon", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Service Body", name: "Service", widget: "markdown" }
    - name: "team"
      label: "Team Members"
      label_singular: "Team Member"
      editor:
          preview: false
      delete: false
      preview_path: "team"
      files:
        - label: "Members"
          name: "members"
          file: "src/_data/settings.json"
          fields:
            - label: Members
              name: members
              widget: list
              allow_add: true
              fields:
                - { label: "Name", name: "name", widget: "string" }
                - { label: "Position", name: "position", widget: "string" }
                - { label: "Bio", name: "bio", widget: "string" }
                - { label: "Background", name: "background", widget: "string" }
                - label: "Image"
                  name: "image"
                  widget: "object"
                  fields:
                    - { label: "Photo", name: "main", widget: "image" }
                    - { label: "Photo Alt", name: "alt", widget: "string" }
                - label: "Social"
                  name: "social"
                  widget: "list"
                  fields:
                    - { label: "Name", name: "name", widget: "string", required: false }
                    - { label: "Link", name: "link", widget: "string", required: false }
    - name: "generalSettings"
      label: "General Settings"
      delete: false # Prevent users from deleting documents in this collection
      editor:
        preview: false
      files:
        - label: "Site Settings"
          name: "siteSettings"
          file: "src/_data/settings.json"
          fields:
            - label: General Settings
              name: siteSettings
              widget: object
              fields:
                - { label: "Company Name", name: "companyName", widget: "string" }
                - { label: "Phone", name: "phone", widget: "string" }
                - { label: "Email", name: "email", widget: "string" }
                - { label: "Address", name: "address", widget: "string" }
            - label: Social Settings
              name: socialSettings
              widget: list
              fields:
                - { label: "Name", name: "socialName", widget: "string" }
                - { label: "Link", name: "socialUrl", widget: "string" }
media_folder: "_site/assets/img"
public_folder: "img"