backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{ slug }}"
    fields:
      - {
        label: "Title",
        name: "title",
        widget: "string"
      }
      - {
        label: "Publish Date",
        name: "date",
        widget: "datetime"
      }
      - {
        label: "Post Body",
        name: "body",
        widget: "markdown"
      }
  - label: "Services"
    name: "services"
    create: true
    folder: "src/services"
    fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Icon", name: "faIcon", widget: "string" }
        - { label: "Description", name: "description", widget: "text" }
        - { label: "Service Body", name: "Service", widget: "markdown" }
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "General"
        label: "Site Settings"
        file: "_data/settings.json"
        fields:
          - { label: "Site Name", name: "siteName", widget: "string" }
          - label: "General Settings"
            name: "generalSettings"
            widget: "object"
            fields:
              - { label: "Phone", name: "phone", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Address", name: "address", widget: "string" }
          - label: "Post Settings"
            name: "posts"
            widget: "object"
            fields:
              - {
                  label: 'Number of posts on frontpage',
                  name: "front_limit",
                  widget: "number",
                  min: 1,
                  max: 10,
                }
              - { label: "Default Author", name: "author", widget: "string" }
              - {
                  label: "Default Thumbnail",
                  name: "thumb",
                  widget: "image",
                  class: "thumb",
                  required: false,
              }
          - label: "Social Settings"
            name: "socials"
            widget: "object"
            fields:
              - {
                  label: "Social Name",
                  name: "socialName",
                  widget: "string",
                  required: false,
                  default: "facebookk"
                }
              - { label: "Url", name: "socialUrl", widget: "string", required: false }

media_folder: "_site/assets/img"
public_folder: "img"