backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{ slug }}"
    fields:
      - {
        label: "Title",
        name: "title",
        widget: "string"
      }
      - {
        label: "Publish Date",
        name: "date",
        widget: "datetime"
      }
      - {
        label: "Post Body",
        name: "body",
        widget: "markdown"
      }
  - label: "Services"
    name: "services"
    create: true
    folder: "src/services"
    fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Icon", name: "faIcon", widget: "string" }
        - { label: "Description", name: "description", widget: "text" }
        - { label: "Service Body", name: "Service", widget: "markdown" }
  - name: "generalSettings"
    label: "General Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - label: "Site Settings"
        name: "siteSettings"
        file: "_data/settings.json"
        fields:
          - label: General Settings
            name: siteSettings
            widget: object
            fields:
              - { label: "Phone", name: "phone", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Address", name: "address", widget: "string" }
          - label: Social Settings
            name: socialSettings
            widget: object
            fields:
              - { label: "facebook Url", name: "facebookUrl", widget: "string", required: false}
              - { label: "twitter Url", name: "twitterUrl", widget: "string", required: false }
media_folder: "_site/assets/img"
public_folder: "img"